name: powergenome
channels:
  - conda-forge
  # - defaults
dependencies:
  - python=3.7 # Remove for tox.ini & setup.py
  - pip
  - conda-forge::catalystcoop.pudl=0.3
  - conda-forge::numpy=1.19
  - jupyterlab
  - black
  - pytest
  - requests
  - beautifulsoup4
  - pyyaml
  - conda-forge::pre-commit
  - isort
  - pre-commit
  - conda-forge::nb_conda_kernels
  - xlrd=1.2
  - conda-forge::fastparquet

  # GIS dependencies from conda-forge
  - conda-forge::fiona
  - conda-forge::geopandas
  - conda-forge::shapely
  - conda-forge::descartes

  - pip:
    - python-dotenv
    - flatten-dict
    - ruamel.yaml
